# Generated by Django 4.1.7 on 2023-03-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFactsPerScoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_grams', models.PositiveSmallIntegerField()),
                ('calories', models.PositiveSmallIntegerField()),
                ('fat', models.PositiveSmallIntegerField()),
                ('carbohydrate', models.PositiveSmallIntegerField()),
                ('protein', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinPowder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=30)),
                ('producer_name', models.CharField(max_length=50)),
                ('flavour', models.CharField(max_length=20)),
                ('quantity_in_grams', models.PositiveSmallIntegerField()),
                ('is_vegan', models.BooleanField()),
                ('scoop_nutrition_facts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nutritionfactsperscoop')),
            ],
        ),
    ]
