SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED

-- Transaction 2
BEGIN TRANSACTION

SELECT * FROM RapBands;

WAITFOR DELAY '00:00:15';

SELECT * FROM RapBands;

COMMIT TRANSACTION;


DELETE FROM RapBands
DELETE FROM RapBandFans

-- how to solve it?
-- using a higher isolation level 
-- such as READ COMMITTED or REPEATABLE READ