SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- solution

-- Transaction 2
BEGIN TRAN
SELECT * FROM RapBands

WAITFOR DELAY '00:00:05'

SELECT * FROM RapBands
COMMIT TRAN


DELETE FROM RapBands